CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    password_hash VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'USER';
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
UPDATE users SET role = 'USER' WHERE role IS NULL;

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

CREATE TABLE IF NOT EXISTS entries (
    id BIGSERIAL PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(2) NOT NULL,
    zipcode VARCHAR(10) NOT NULL,
    price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    picture_url TEXT,
    status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'CLOSED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE entries ADD COLUMN IF NOT EXISTS address VARCHAR(255);
ALTER TABLE entries ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE entries ADD COLUMN IF NOT EXISTS state VARCHAR(2);
ALTER TABLE entries ADD COLUMN IF NOT EXISTS zipcode VARCHAR(10);
ALTER TABLE entries ADD COLUMN IF NOT EXISTS price NUMERIC(12, 2);
ALTER TABLE entries ADD COLUMN IF NOT EXISTS picture_url TEXT;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS picture_urls TEXT NOT NULL DEFAULT '[]';
ALTER TABLE entries ADD COLUMN IF NOT EXISTS status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE entries DROP COLUMN IF EXISTS name;
ALTER TABLE entries DROP COLUMN IF EXISTS description;
CREATE INDEX IF NOT EXISTS idx_entries_status ON entries (status);
